# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('char_sheet', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Classes',
            new_name='Background',
        ),
        migrations.RenameModel(
            old_name='Races',
            new_name='PlayerClass',
        ),
        migrations.RenameModel(
            old_name='Backgrounds',
            new_name='Race',
        ),
    ]
