# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 23:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('char_sheet', '0002_auto_20161111_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='background',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='char_sheet.Background'),
        ),
        migrations.AlterField(
            model_name='character',
            name='player_class',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='char_sheet.PlayerClass'),
        ),
        migrations.AlterField(
            model_name='character',
            name='race',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='char_sheet.Race'),
        ),
    ]
