# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 23:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('char_sheet', '0004_auto_20161111_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='background',
            name='pero',
        ),
        migrations.RemoveField(
            model_name='playerclass',
            name='he',
        ),
        migrations.RemoveField(
            model_name='race',
            name='te',
        ),
    ]
