# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 22:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('char_sheet', '0006_auto_20161111_2320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='proficiencies_mask',
        ),
        migrations.AddField(
            model_name='character',
            name='proficiencies',
            field=models.CharField(default='0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0', max_length=72, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AddField(
            model_name='playerclass',
            name='hit_die',
            field=models.IntegerField(default=8),
        ),
        migrations.AddField(
            model_name='playerclass',
            name='save_proficiencies',
            field=models.CharField(default='0,0,0,0,0,0', max_length=12, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
