# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 03:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('char_sheet', '0007_auto_20161118_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='playerclass',
            name='primary_ability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playerclass',
            name='skill_proficiencies',
            field=models.CharField(default='0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0', max_length=36, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AddField(
            model_name='playerclass',
            name='skills_number',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='race',
            name='mandatory_ability_increases',
            field=models.CharField(default='0,0,0,0,0,0', max_length=12, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AddField(
            model_name='race',
            name='optional_ability_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='race',
            name='size_category',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='race',
            name='speed',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='background',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='alignment',
            field=models.CharField(default='NN', max_length=2),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='character',
            name='notes',
            field=models.CharField(default='', max_length=4096),
        ),
        migrations.AlterField(
            model_name='playerclass',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='playerclass',
            name='save_proficiencies',
            field=models.CharField(default='0,1', max_length=4, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AlterField(
            model_name='race',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
