# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('char_sheet', '0008_auto_20161119_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='race',
            name='darkvision',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='race',
            name='subrace_of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='char_sheet.Race'),
        ),
    ]
