# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 23:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('char_sheet', '0009_auto_20161119_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Armor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('base_armor_class', models.IntegerField(default=14)),
                ('max_dex', models.IntegerField(default=9001)),
                ('min_str', models.IntegerField(default=0)),
                ('stealth_disadvantage', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('damage_roll', models.CharField(default='1d6', max_length=255)),
                ('damage_type', models.CharField(default='b', max_length=1)),
                ('versatile_damage', models.CharField(max_length=255, null=True)),
                ('short_range', models.IntegerField(default=0)),
                ('long_range', models.IntegerField(default=0)),
                ('properties', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('cost', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('weight', models.DecimalField(decimal_places=5, default=0, max_digits=10)),
                ('armor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='char_sheet.Armor')),
                ('attack', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='char_sheet.Attack')),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='can_edit',
            field=models.ManyToManyField(related_name='_character_can_edit_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='character',
            name='can_view',
            field=models.ManyToManyField(related_name='_character_can_view_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='character',
            name='owner',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
