# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-02 02:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('char_sheet', '0011_auto_20161121_0000'),
    ]

    operations = [
        migrations.AddField(
            model_name='background',
            name='skill_proficiencies',
            field=models.CharField(default='0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0', max_length=36, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AddField(
            model_name='character',
            name='current_hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='character',
            name='equipment',
            field=models.ManyToManyField(to='char_sheet.Item'),
        ),
        migrations.AddField(
            model_name='character',
            name='equipment_quantities',
            field=models.CharField(blank=True, max_length=4096, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AddField(
            model_name='character',
            name='temp_hp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='generic_proficiency',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='requires_proficiency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playerclass',
            name='spell_slots',
            field=models.CharField(default='0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0', max_length=220, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
        migrations.AddField(
            model_name='playerclass',
            name='spells_known',
            field=models.IntegerField(default=0),
        ),
    ]
